# Description: Configuration file for the I-80 dataset
description: I-80 dataset by NGSIM

dataset: i80
seed: 42
sample_freq: 10
downsample: 2
input_len: 2
output_len: 5
n_inputs: 7
n_outputs: 7
skip_lc_samples: 10  # (1 second)
skip_lk_samples: 40  # (4 seconds)

# Graph
lane_graph:
  buffer: 2.0
  spacing: 10.0

# Recordings
recordings:
  0400pm-0415pm:
    include: true
  0500pm-0515pm:
    include: true
  0515pm-0530pm:
    include: true

