# Description: Configuration file for the Lyft Level 5 dataset
description: LyftLvl5 dataset

dataset: lyft
seed: 42
sample_freq: 10 # Hz
downsample: 2
skip_samples: 20  # (2.0 sec)
input_len: 2
output_len: 5
n_inputs: 7
n_outputs: 7
ego_only: true  # center on ego vehicle only
lane_graph_radius: 125.0  # Radius for lane graph extraction in meters

# Recordings
recordings: true