# Description: Configuration file for the nuScenes dataset
description: nuScenes dataset

dataset: nuscenes
seed: 42
sample_freq: 2
downsample: 1
ori_dt: 0.5           # Original sampling time is 0.5s
dt: 0.2
skip_samples: 1       # (0.5 sec)
input_len: 2
output_len: 6
n_inputs: 7
n_outputs: 7
lane_graph_radius: 200.0  # Radius for lane graph extraction in meters