# Description: Configuration file for the openDD dataset
description: openDD dataset

dataset: openDD
seed: 42
sample_freq: 30
downsample: 6
skip_samples: 75 # (2.5 seconds)
input_len: 2
output_len: 5
n_inputs: 7
n_outputs: 7

# Recordings
recordings:
  rdb1:
    include: true
  rdb2:
    include: true
  rdb3:
    include: true
  rdb4:
    include: true
  rdb5:
    include: true
  rdb6:
    include: true
  rdb7:
    include: true