"""Public runtime entrypoints."""

from __future__ import annotations

from typing import TYPE_CHECKING

from dronalize.datasets.registry import get
from dronalize.io.backends.registry import build_writer_factory
from dronalize.runtime._internal.resolve import build_plan
from dronalize.runtime._internal.runner import open_execution_session
from dronalize.runtime.types import ExecutionResult

if TYPE_CHECKING:
    from collections.abc import Iterator

    from dronalize.core.scene import Scene
    from dronalize.runtime.types import ExecutionPlan, ExecutionRequest


def resolve_request(request: ExecutionRequest) -> ExecutionPlan:
    """Resolve one processing request into an execution-ready plan.

    Parameters
    ----------
    request : ExecutionRequest
        The dataset-processing request to resolve. This includes all user-provided
        parameters, paths, and overrides.

    Returns
    -------
    ExecutionPlan
        A fully resolved execution plan, including all derived parameters,
        loader requests, and output plans. This plan is ready to be executed
        directly or streamed using
        [`execute_plan`][dronalize.runtime.execute_plan] or
        [`stream_plan`][dronalize.runtime.stream_plan], respectively.

    """
    descriptor = get(request.dataset)
    return build_plan(descriptor=descriptor, request=request)


def execute_request(request: ExecutionRequest) -> ExecutionResult:
    """Resolve and execute one dataset-processing request.

    This is a convenience method that combines the resolution and execution
    steps into a single call. It is suitable for simple use cases where the user
    does not need to inspect or modify the execution plan before running it.

    Parameters
    ----------
    request : ExecutionRequest
        The dataset-processing request to resolve and execute. This includes all
        user-provided parameters, paths, and overrides.

    """
    return execute_plan(resolve_request(request))


def execute_plan(plan: ExecutionPlan) -> ExecutionResult:
    """Execute one resolved plan and collect final counters and output paths.

    This will start the execution where the main objective is to process all
    scenes and write them to disk

    Parameters
    ----------
    plan : ExecutionPlan
        The execution plan to run. This should be a fully resolved plan.

    Returns
    -------
    ExecutionResult
        Summary of the execution.
    """
    with open_execution_session(plan) as run:
        run.executor.execute(writer_factory=build_writer_factory(plan))
        plan.write_manifests()
        progress = run.executor.progress()
        return ExecutionResult(
            dataset=plan.dataset,
            output_dir=plan.output_dir,
            storage_backend=plan.storage_backend,
            processed_sources=progress.processed_sources,
            candidate_scenes=progress.candidate_scenes,
            selected_scenes=progress.selected_scenes,
            split_counts=progress.split_counts,
        )


def stream_plan(plan: ExecutionPlan) -> Iterator[Scene]:
    """Execute one resolved plan and yield generated scenes.

    Alternative to [`execute_plan`][dronalize.runtime.execute_plan] for use
    cases where the actual scene objects are the main output of interest.

    Parameters
    ----------
    plan : ExecutionPlan
        The execution plan to run. This should be a fully resolved plan.

    Yields
    ------
    Scene
        Scenes generated by the execution. This allows for processing results in
        a streaming fashion, without waiting for the entire execution to complete.

    """
    with open_execution_session(plan) as run:
        yield from run.executor.execute_yield()
