"""Internal runtime executors."""

from __future__ import annotations

import functools
import logging
import multiprocessing as mp
import threading
from collections import deque
from collections.abc import Callable, Generator, Iterable, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from multiprocessing.pool import Pool
from multiprocessing.synchronize import Event
from multiprocessing.util import Finalize
from typing import TYPE_CHECKING, Any, Protocol, TypeVar

from typing_extensions import override

from dronalize.core.scene import Scene
from dronalize.io.base import DatasetWriter
from dronalize.runtime.processor import RuntimeProcessor
from dronalize.runtime.state import Progress, SharedResources, SplitCounts, WorkerRuntime

if TYPE_CHECKING:
    from dronalize.core.typing import P
    from dronalize.processing.loading.models import DatasetSource
    from dronalize.runtime.types import ExecutionPlan

AnyEvent = Event | threading.Event
WriterFactory = Callable[[int | None], DatasetWriter]
ReturnT = TypeVar("ReturnT", int, list[Scene])
_ctx: WorkerRuntime

logger = logging.getLogger(__name__)


class Executor(Protocol):
    """Shared protocol for sequential and parallel execution of a plan."""

    def execute(self, writer_factory: WriterFactory) -> None:
        """Execute the plan, writing scenes based on the provided writer factory.

        Parameters
        ----------
        writer_factory: Callable[[int], DatasetWriter]
            A factory function that takes a worker ID and returns a
            `DatasetWriter` instance for that worker to write scenes with.

        Notes
        -----
        It is up to the dataset writer implementation to handle any necessary
        synchronization for parallel execution, such as locking or buffering, to
        ensure that scenes are written correctly without conflicts or data
        corruption.

        """
        ...

    def execute_yield(self) -> Iterator[Scene]:
        """Execute the plan, yielding scenes one by one as they are generated.

        Returns
        -------
        Iterator[Scene]
            An iterator that yields `Scene` objects as they are generated by
            executing the plan.
        """
        ...

    def progress_event(self) -> AnyEvent:
        """Return an event that is set whenever progress is updated.

        This can be used by external code to wait for progress updates or to
        trigger actions whenever progress changes.

        Returns
        -------
        AnyEvent
            An event object (either `threading.Event` or
            `multiprocessing.synchronize.Event`) that is set whenever the
            executor's progress is updated.

        """
        ...

    def is_running(self) -> bool:
        """Flag indicating whether the executor is currently running.

        Returns
        -------
        bool
            `True` if the executor is currently running, `False` otherwise.
        """
        ...

    def progress(self) -> Progress:
        """Return the current progress of the executor.

        Returns
        -------
        Progress
            A `Progress` object containing information about the current progress
            of the executor, such as the number of processed sources, candidate
            scenes, selected scenes, total sources, active workers, split counts,
            and whether screening is enabled.
        """
        ...


@dataclass(slots=True)
class ExecutionSession:
    plan: ExecutionPlan
    executor: Executor


@contextmanager
def open_execution_session(plan: ExecutionPlan) -> Generator[ExecutionSession, None, None]:
    """Open one plan with initialized resources, processor, and executor."""
    with plan.descriptor.open_resources(plan.data_root, plan.loader) as resources:
        logger.debug("Opening execution session", extra={"dataset": plan.dataset})
        loader = plan.descriptor.build_loader(
            root=plan.data_root, request=plan.loader, resources=resources
        )
        processor = RuntimeProcessor.from_plan(plan, loader)
        executor = _build_executor(plan, processor)
        yield ExecutionSession(plan=plan, executor=executor)


def _build_executor(plan: ExecutionPlan, processor: RuntimeProcessor) -> Executor:
    if plan.parallel:
        logger.debug("Using parallel executor", extra={"dataset": plan.dataset})
        return ParallelExecutor(
            processor, workers=plan.workers, chunksize=plan.runtime.chunksize, limit=plan.limit
        )
    logger.debug("Using sequential executor", extra={"dataset": plan.dataset})
    return SequentialExecutor(processor, limit=plan.limit)


class SequentialExecutor(Executor):
    """Single-process executor for internal runtime execution.

    Parameters
    ----------
    processor: RuntimeProcessor
        The runtime processor to execute, containing logic and cofigurations.
    limit: int | None, optional
        An optional limit on the total number of scenes to select. If None, no
        limit will be applied. Default is None.
    """

    def __init__(self, processor: RuntimeProcessor, *, limit: int | None = None) -> None:
        self._processor: RuntimeProcessor = processor
        self._limit: int | None = limit
        self._candidate_scene_counter: int = 0
        self._selected_scene_counter: int = 0
        self._source_counter: int = 0
        self._split_counts: SplitCounts = {"unsplit": 0, "train": 0, "val": 0, "test": 0}
        self._screening_enabled: bool = processor.screening_enabled()
        self._total_sources: int | None = processor.total_sources()
        self._update_event: threading.Event = threading.Event()
        self._running: bool = False

    @override
    def execute(self, writer_factory: WriterFactory) -> None:
        writer = writer_factory(0)
        try:
            for scene in self._generate_and_track():
                writer.write(scene)
        finally:
            writer.finish_local()
            writer.finish_final()

    @override
    def execute_yield(self) -> Iterator[Scene]:
        yield from self._generate_and_track()

    @override
    def progress(self) -> Progress:
        return Progress(
            running=self._running,
            processed_sources=self._source_counter,
            candidate_scenes=self._candidate_scene_counter,
            selected_scenes=self._selected_scene_counter,
            total_sources=self._total_sources,
            scene_limit=self._limit,
            active_workers=1 if self._running else 0,
            split_counts=self._split_counts,
            screening_enabled=self._screening_enabled,
        )

    @override
    def progress_event(self) -> threading.Event:
        return self._update_event

    @override
    def is_running(self) -> bool:
        return self._running

    def _generate_and_track(self) -> Iterable[Scene]:
        self._running = True
        self._update_event.set()

        try:
            yield from self._inner_iter_sources()
        finally:
            self._running = False
            self._update_event.set()

    def _inner_iter_sources(self) -> Iterable[Scene]:
        for source in self._processor.iter_sources():
            if self._selected_scene_limit_reached():
                break
            self._source_counter += 1
            self._update_event.set()
            for candidate in self._processor.iter_candidates(source):
                self._record_candidate_scene()
                if not candidate.passes_screening:
                    continue
                scene_number = self._claim_selected_scene()
                if scene_number is None:
                    return
                scene = self._processor.materialize(candidate, scene_number)
                split_key = (
                    "unsplit" if scene.split_assignment is None else scene.split_assignment.value
                )
                self._split_counts[split_key] += 1
                self._update_event.set()
                yield scene

    def _record_candidate_scene(self) -> None:
        self._candidate_scene_counter += 1
        self._update_event.set()

    def _claim_selected_scene(self) -> int | None:
        if self._selected_scene_limit_reached():
            return None
        scene_number = self._selected_scene_counter
        self._selected_scene_counter += 1
        self._update_event.set()
        return scene_number

    def _selected_scene_limit_reached(self) -> bool:
        return self._limit is not None and self._selected_scene_counter >= self._limit


class ParallelExecutor(Executor):
    """Parallel executor for internal runtime execution.

    Parameters
    ----------
    processor: RuntimeProcessor
        The runtime processor to execute, containing logic and cofigurations.
    chunksize: int | None, optional
        The number of sources to process in each worker batch. If None, an
        optimal chunksize will be estimated based on a simple heuristic. Default
        is None.
    workers: int | None, optional
        The number of worker processes to use for parallel execution. If None,
        the number of CPU cores will be used. Default is None.
    limit: int | None, optional
        An optional limit on the total number of scenes to select across all
        workers. If None, no limit will be applied. Default is None.
    """

    def __init__(
        self,
        processor: RuntimeProcessor,
        *,
        chunksize: int | None = None,
        workers: int | None = None,
        limit: int | None = None,
    ) -> None:
        if workers is not None and workers <= 1:
            msg = "number of processes must be greater than 1 for parallel execution."
            raise ValueError(msg)
        self._processor: RuntimeProcessor = processor
        self._shared: SharedResources = SharedResources.create(scene_limit=limit)
        total_sources = processor.total_sources()
        self._chunksize: int = chunksize or self._optimal_chunksize(total_sources, workers)
        self._limit: int | None = limit
        self._processes: int | None = workers
        self._num_sources: int | None = total_sources
        self._screening_enabled: bool = processor.screening_enabled()
        self._running: bool = False

    @override
    def execute(self, writer_factory: WriterFactory) -> None:
        _ = deque(
            self._execute_parallel(
                self._process_fn_write,
                self._processor.iter_sources(),
                _init_write_worker,
                self._shared,
                self._processor,
                writer_factory,
            ),
            maxlen=0,
        )
        writer_factory(None).finish_final()

    @override
    def execute_yield(self) -> Iterator[Scene]:
        for scenes in self._execute_parallel(
            self._process_fn_yield,
            self._processor.iter_sources(),
            _init_worker,
            self._shared,
            self._processor,
        ):
            yield from scenes

    @override
    def progress(self) -> Progress:
        with self._shared.progress.snapshot_lock:
            return Progress(
                running=self._running,
                processed_sources=self._shared.progress.source_counter.value,
                candidate_scenes=self._shared.progress.candidate_scene_counter.value,
                selected_scenes=self._shared.progress.selected_scene_counter.value,
                active_workers=self._shared.progress.active_workers.value,
                total_sources=self._num_sources,
                scene_limit=self._limit,
                split_counts=self._shared.progress.split_counts(),
                screening_enabled=self._screening_enabled,
            )

    @override
    def progress_event(self) -> Event:
        return self._shared.progress.update_event

    @override
    def is_running(self) -> bool:
        return self._running

    @staticmethod
    def _process_fn_write(source: DatasetSource[Any]) -> int:
        if _ctx.writer is None:
            msg = "DatasetWriter was not initialized for this worker process."
            raise ValueError(msg)
        if _ctx.processor is None:
            msg = "Runtime processor was not initialized for this worker process."
            raise ValueError(msg)
        if _ctx.shared.progress.selected_scene_limit_reached(_ctx.shared.scene_limit):
            return 0
        selected_scenes = 0
        for scene in ParallelExecutor._generate_scenes(_ctx.processor, source):
            _ctx.shared.progress.record_split(scene.split_assignment)
            _ctx.writer.write(scene)
            selected_scenes += 1
        _ = _ctx.shared.progress.increment_source()
        return selected_scenes

    @staticmethod
    def _process_fn_yield(source: DatasetSource[Any]) -> list[Scene]:
        if _ctx.processor is None:
            msg = "Runtime processor was not initialized for this worker process."
            raise ValueError(msg)
        if _ctx.shared.progress.selected_scene_limit_reached(_ctx.shared.scene_limit):
            return []
        _ = _ctx.shared.progress.increment_source()
        scenes = list(ParallelExecutor._generate_scenes(_ctx.processor, source))
        for scene in scenes:
            _ctx.shared.progress.record_split(scene.split_assignment)
        return scenes

    @staticmethod
    def _generate_scenes(
        processor: RuntimeProcessor, source: DatasetSource[Any]
    ) -> Iterator[Scene]:
        if _ctx.shared.progress.selected_scene_limit_reached(_ctx.shared.scene_limit):
            return
        claim_selected_scene = functools.partial(
            _ctx.shared.progress.claim_selected_scene, _ctx.shared.scene_limit
        )
        for candidate in processor.iter_candidates(source):
            _ = _ctx.shared.progress.record_candidate_scene()
            if not candidate.passes_screening:
                continue
            scene_number = claim_selected_scene()
            if scene_number is None:
                return
            yield processor.materialize(candidate, scene_number)

    def _execute_parallel(
        self,
        process_fn: Callable[[DatasetSource[Any]], ReturnT],
        payloads: Iterable[DatasetSource[Any]],
        initializer: Callable[P, object],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> Iterable[ReturnT]:
        self._shared.reset()
        pool_initializer = functools.partial(initializer, *args, **kwargs)
        self._running = True
        self.progress_event().set()
        pool: Pool | None = None
        completed = False
        try:
            pool = Pool(self._processes, initializer=pool_initializer)
            yield from pool.imap_unordered(process_fn, payloads, self._chunksize)
            completed = True
        finally:
            if pool is not None:
                if completed:
                    pool.close()
                else:
                    pool.terminate()
                pool.join()
            self._running = False
            self.progress_event().set()

    @staticmethod
    def _optimal_chunksize(num_sources: int | None, num_processes: int | None) -> int:
        if num_sources is None:
            return 1
        process_count = num_processes or mp.cpu_count()
        chunksize, extra = divmod(num_sources, process_count * 4)
        chunksize += int(extra > 0)
        return max(chunksize, 1)


def _init_worker(
    shared: SharedResources,
    processor: RuntimeProcessor | None = None,
    *,
    with_finalize: bool = True,
) -> None:
    global _ctx  # noqa: PLW0603
    worker_id = shared.registry.next_worker()
    shared.progress.worker_started()
    _ctx = WorkerRuntime(shared=shared, worker_id=worker_id, processor=processor)
    if with_finalize:

        def cleanup() -> None:
            _ = _ctx.shared.progress.worker_stopped()

        _ = Finalize(obj=None, callback=cleanup, exitpriority=10)


def _init_write_worker(
    shared: SharedResources,
    processor: RuntimeProcessor,
    writer_factory: Callable[[int | None], DatasetWriter],
) -> None:
    global _ctx  # noqa: PLW0602
    _init_worker(shared, processor, with_finalize=False)
    writer: DatasetWriter | None = None
    try:
        writer = writer_factory(_ctx.worker_id)
        _ctx.writer = writer
    except Exception:
        _ = _ctx.shared.progress.worker_stopped()
        raise

    def cleanup() -> None:
        current_writer = _ctx.writer
        if current_writer is None:
            return
        try:
            current_writer.finish_local()
        finally:
            _ = _ctx.shared.progress.worker_stopped()

    _ = Finalize(obj=None, callback=cleanup, exitpriority=10)


__all__ = ["AnyEvent", "Executor", "ParallelExecutor", "SequentialExecutor", "WriterFactory"]
