"""Internal executor protocols."""

from __future__ import annotations

import threading
from collections.abc import Callable, Iterator
from multiprocessing.synchronize import Event
from typing import TYPE_CHECKING, Protocol

from dronalize.io.base import DatasetWriter

if TYPE_CHECKING:
    from dronalize.core.scene.model import Scene
    from dronalize.runtime._internal.state import Progress

AnyEvent = Event | threading.Event
WriterFactory = Callable[[int], DatasetWriter]


class Executor(Protocol):
    """Shared protocol for sequential and parallel execution of a plan."""

    def execute(self, writer_factory: WriterFactory) -> None:
        """Execute the plan, writing scenes based on the provided writer factory.

        Parameters
        ----------
        writer_factory: Callable[[int], DatasetWriter]
            A factory function that takes a worker ID and returns a
            `DatasetWriter` instance for that worker to write scenes with.

        Notes
        -----
        It is up to the dataset writer implementation to handle any necessary
        synchronization for parallel execution, such as locking or buffering, to
        ensure that scenes are written correctly without conflicts or data
        corruption.

        """
        ...

    def execute_yield(self) -> Iterator[Scene]:
        """Execute the plan, yielding scenes one by one as they are generated.

        Returns
        -------
        Iterator[Scene]
            An iterator that yields `Scene` objects as they are generated by
            executing the plan.
        """
        ...

    def progress_event(self) -> AnyEvent:
        """Return an event that is set whenever progress is updated.

        This can be used by external code to wait for progress updates or to
        trigger actions whenever progress changes.

        Returns
        -------
        AnyEvent
            An event object (either `threading.Event` or
            `multiprocessing.synchronize.Event`) that is set whenever the
            executor's progress is updated.

        """
        ...

    def is_running(self) -> bool:
        """Flag indicating whether the executor is currently running.

        Returns
        -------
        bool
            `True` if the executor is currently running, `False` otherwise.
        """
        ...

    def progress(self) -> Progress:
        """Return the current progress of the executor.

        Returns
        -------
        Progress
            A `Progress` object containing information about the current progress
            of the executor, such as the number of processed sources, candidate
            scenes, selected scenes, total sources, active workers, split counts,
            and whether screening is enabled.
        """
        ...
