# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/camera_tokens.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import preprocessing.road_network.waymo.protos.dataset_pb2 as dataset__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1aprotos/camera_tokens.proto\x12\x12waymo.open_dataset\x1a\rdataset.proto"\\\n\x0c\x43\x61meraTokens\x12\x38\n\x0b\x63\x61mera_name\x18\x01 \x01(\x0e\x32#.waymo.open_dataset.CameraName.Name\x12\x12\n\x06tokens\x18\x02 \x03(\rB\x02\x10\x01"L\n\x11\x46rameCameraTokens\x12\x37\n\rcamera_tokens\x18\x01 \x03(\x0b\x32 .waymo.open_dataset.CameraTokens'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "protos.camera_tokens_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _CAMERATOKENS.fields_by_name["tokens"]._options = None
    _CAMERATOKENS.fields_by_name["tokens"]._serialized_options = b"\020\001"
    _CAMERATOKENS._serialized_start = 65
    _CAMERATOKENS._serialized_end = 157
    _FRAMECAMERATOKENS._serialized_start = 159
    _FRAMECAMERATOKENS._serialized_end = 235
# @@protoc_insertion_point(module_scope)
